main: pl.masarniamc.essentials.Main
name: MasarniaMCEssentials
version: 1.0
author: DeeRave
description: Komendy i podstawowe funkcje serwera.
api-version: 1.16
commands:
  discord:
    description: Wyswietla zaproszenie do discorda serwerowego.
    usage: "Poprawne uzycie: /discord"
  website:
    description: Wyswietla serwerowa strone www.
    usage: "Poprawne uzycie: /www"
    aliases: www