name: DiscoArmor
main: masarniamc.discoarmor.Main
version: 1.0
author: DeeRave
description: Disco Zbroja.
api-version: 1.15
commands:
  discoarmor:
    description: Daje graczowi disco zboje.
    usage: Wpisz /discoarmor [player].